version: 2

jobs:
  build:
    docker:
      - image: "tobante/gcc-cmake-juce:8.3"
    resource_class: medium
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run:
          name: Installing dependecies
          command: "apt-get update -qq && apt-get install -y -qq --no-install-recommends lcov libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglu1-mesa-dev"
      - run:
          name: Build
          command: "make coverage"
      - run:
          name: Collect coverage data
          command: "bash <(curl -s https://codecov.io/bash) -f build_coverage/cov.info"
